"""empty message

Revision ID: 3fc84d610472
Revises: 
Create Date: 2025-11-23 19:33:59.900058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fc84d610472'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('team_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_name'], ['teams.team_name'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pull_requests',
    sa.Column('pull_request_id', sa.String(), nullable=False),
    sa.Column('pull_request_name', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('MERGED', 'OPEN', name='list_visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pull_request_id')
    )
    op.create_table('assigned_users',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('pull_request_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.pull_request_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigned_users')
    op.drop_table('pull_requests')
    op.drop_table('users')
    op.drop_table('teams')
    # ### end Alembic commands ###
