"""empty message

Revision ID: 592586b3d15d
Revises: 3fc84d610472
Create Date: 2025-11-23 20:52:59.174125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '592586b3d15d'
down_revision = '3fc84d610472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.alter_column('merged_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.alter_column('merged_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
